# Generated by Django 3.2.4 on 2021-09-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_date',
        ),
    ]
